import os
from dotenv import load_dotenv

load_dotenv()

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

DEFAULT_LANGUAGE = "uk"

INITIAL_HEALTH = 100
INITIAL_SUIT_CHARGE = 100
INITIAL_FOOD = 5
INITIAL_WATER = 5
SUIT_CHARGE_PER_OUTING = 25
FOOD_PER_DAY = 1
WATER_PER_DAY = 1

SUIT_CHARGE_RECOVERY_AMOUNT = 20

ORGANIZATION_START_DAY = 7
TADMAVRIEL_START_DAY = 10
REJECTION_START_DAY = 6
